import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from '../components/Header'
import { About } from '../components/About'
import { Navbar } from '../components/Navbar'
import { Stack } from '../components/Stack'
import { Projects } from '../components/Projects'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Andie Perez</title>
        <meta name="Andrea Perez Portfolio" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Header />
      <About />
      <Stack />
      <Projects />
      <Footer />
    </div>
  )
}
