import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header } from '../components/Header'
import { About } from '../components/About'
import { Navbar } from '../components/Navbar'
import { Stack } from '../components/Stack'
import { Projects } from '../components/Projects'
import { Footer } from '../components/Footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Andie Perez</title>
        <meta name="Andrea Perez Portfolio" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-T4NYMLDXZT"
        />

        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-T4NYMLDXZT', { page_path: window.location.pathname });
            `,
          }}
        />
      </Head>
      <Navbar />
      <Header />
      <About />
      <Stack />
      <Projects />
      <Footer />
    </div>
  )
}
